### ISSUE TITLE
Issues related to use of backtick

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/eslint-config-digitalbazaar#15]
https://github.com/digitalbazaar/eslint-config-digitalbazaar/blob/master/index.js#L50

That rule doesn't like
```js
const string = `imastring`;
```
but it's ok with
```js
const string = `imastring${withvar}`;
```
and it doesn't like:
```js
const string = `'quotedstring' is a thing.`;
```

**Comment by davidlehn** [comment]
https://eslint.org/docs/rules/quotes
Probably need to add one or more of the options like `allowTemplateLiterals`?

**Comment by aljones15** [comment]
added allowTemplateLiterals to the pending PR so try it @mattcollier and see if it works.

**Comment by aljones15** [comment]
@mattcollier is this issue resolved now?

**Comment by mattcollier** [comment]
Yes, ty.
