### ISSUE TITLE
no trailing commas

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/eslint-config-digitalbazaar#17]
Current lint rules allow trailing commas

```
[1,2,3,]
// this is ok
// however @gannan08 wants this
[1,2]
// no trailing commas
```

rule is very simple to set:
https://eslint.org/docs/rules/comma-dangle

**Comment by mattcollier** [comment]
First, comma dangle is not allowed in any case in inline arrays or objects.  The use case we are discussing is 
```
const x = {
  a: 'foo',
  b: 'bar',
};
const y = [
  'a',
  'b',
];
```
Here's what I said earlier about this:

what happens in linting rules is one thing, but I object to changing any rule related to allowing trailing comma in regular js code. The premise of allowing trailing comma is that it can lead to cleaner diffs, not saving someone from having to type a comma. So, with code that already has a trailing comma in place in an array or an object, means that the diff can be for just one line if a single property or array member is added.

**Comment by aljones15** [comment]
ahhh ok did not know that.

**Comment by gannan08** [comment]
I just want to remove the comma dangle in the eslint configuration template file. I am not proposing any rule changes that restrict other developers.

**Comment by mattcollier** [comment]
I have no objection to removing the dangling commas from the templates.

**Comment by aljones15** [comment]
removing them.

**Comment by aljones15** [comment]
@mattcollier @gannan08  can this be closed?

**Comment by aljones15** [comment]
closing this as it has been open for a while.
