### ISSUE TITLE
Dynamic Imports

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/eslint-config-digitalbazaar#20]
Evidently we're supposed to use a babel-parser plugin to allow `import()` until it becomes stage 4

https://github.com/eslint/eslint/issues/7764#issuecomment-266966062

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Specifications

This is currently producing errors in places where it is used.

**Comment by aljones15** [comment]
yeah the polyfill is definitely required. how is that related to this project?

**Comment by aljones15** [comment]
@mattcollier ok fixed this today:

https://github.com/digitalbazaar/bedrock-vue-wizard/commit/41276f2d444b63d14203291cf63d1309a928d161

basically 

```
npm i -D babel-eslint

// add this to .eslintrc.js inside dir with dynamic imports

module.exports = {
  parser: 'babel-eslint',
... }

// create a valid babel.config.js file
module.exports = function(api) {
  return {
    plugins: ['babel-plugin-syntax-dynamic-import']
  }
}
```

close if you can do it. commit linked should help.

**Comment by mattcollier** [comment]
@aljones15 we need the `import ()` syntax to work in basically all of our front end modules correct?  Is there some way we can include this in our eslint-config-digitalbazaar module?  We don't want devs to have to deal with this in all the places.  Can this be part of the vue rules or something?

**Comment by aljones15** [comment]
@mattcollier really we only need it in the test projects I've found. we could add it parser: 'babel-eslint' to the vue template I suppose. not sure on adding it to the rules directly though. I think we need a boiler plate test for the various bedrock-vue projects with this setup by default.

**Comment by aljones15** [comment]
```
{
    "parser": "vue-eslint-parser",
    "parserOptions": {
        "parser": "babel-eslint",
        "sourceType": "module",
        "allowImportExportEverywhere": false
    }
}
```
via https://github.com/mysticatea/vue-eslint-parser
