### ISSUE TITLE
Add rules concerning dangling commas

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/eslint-config-digitalbazaar#49]
https://eslint.org/docs/rules/comma-dangle

When I joined DB I was told not to use dangling commas like this:

```js
{
  foo: true,
  bar: true,
}
```

however it appears this might not be the consensus on this issue.

Please discuss, and thumbs up if you are ok with this new rule:

```js
/*eslint comma-dangle: ["error", "always"]*/

var foo = {
    bar: "baz",
    qux: "quux",
};
// no error
var arr = [1,2,];

foo({
  bar: "baz",
  qux: "quux",
});
// no error

var foo = {
    bar: "baz",
    qux: "quux"
};
// error

var arr = [1,2];

foo({
  bar: "baz",
  qux: "quux"
});
// error
```

**Comment by mattcollier** [comment]
There is an existing rule: https://github.com/digitalbazaar/eslint-config-digitalbazaar/blob/master/index.js#L14

**Comment by mattcollier** [comment]
And an old issue: https://github.com/digitalbazaar/eslint-config-digitalbazaar/issues/17

**Comment by dlongley** [comment]
-1. I'm not ok with making it an error to have no dangling comma.

**Comment by aljones15** [comment]
I'm going to go ahead and close this provided we are at consensus that we are ok with a dangling comma on multi-line, but it is also ok to not have a dangling comma if the dev chooses.

**Comment by dlongley** [comment]
Yup, I think that's the consensus we have (i.e., that we don't have consensus to use/not use dangling commas on multilines, so we allow devs to choose).

**Comment by aljones15** [comment]
@mattcollier do you agree with @dlongley here? if so I'll close this.

**Comment by aljones15** [comment]
48 hours is enough time. I'm closing this and assuming that as a company we allow developers to have dangling commas or not at their discretion. I also agree with that rule.
